const words = {
  easy: [

      { word: "indira", hint: "First and only female Prime Minister of India" },
      { word: "kalpana", hint: "First Indian woman in space" },
      { word: "mary", hint: "Indian boxing champion and Olympic medalist" },
      { word: "lata", hint: "Legendary Indian playback singer known as the 'Nightingale of India'" },
      { word: "kiran", hint: "India's first woman IPS officer" },
      { word: "ptusha", hint: "Sprinter known as the 'Payyoli Express'" },
      { word: "mirabai", hint: "Indian weightlifter who won silver at the Tokyo Olympics" },
      { word: "deepika", hint: "Indian archer and Olympian" },
      { word: "sania", hint: "India’s top female tennis player" },
      { word: "pv sindhu", hint: "Badminton champion who won silver and bronze Olympic medals" },
      { word: "bhavani", hint: "First Indian fencer to qualify for Olympics" },
      { word: "hima", hint: "Sprinter known as the 'Dhing Express'" },
      { word: "mithali", hint: "Captain of Indian women’s national cricket team" },
      { word: "sunita", hint: "NASA astronaut with Indian origin, flew on space shuttle missions" },
      { word: "rekha", hint: "Veteran Indian actress known for her powerful roles" },
      { word: "sushmita", hint: "First Indian woman to win Miss Universe (1994)" },
      { word: "priyanka", hint: "Bollywood actress and Miss World 2000" },
      { word: "kangana", hint: "Known for bold roles and women-centric films" },
      { word: "rani", hint: "Famous Bollywood actress known for impactful roles" },
      { word: "shreya", hint: "Popular Indian playback singer with a melodious voice" },
      { word: "dutee", hint: "Indian sprinter and LGBTQ+ advocate" },
      { word: "alia", hint: "Young Bollywood actress with multiple blockbuster films" },
      { word: "anushka", hint: "Actress and producer, married to cricketer Virat Kohli" },
      { word: "kareena", hint: "Bollywood actress known for her iconic roles" },
      { word: "kajol", hint: "Award-winning actress and 90s Bollywood star" },
      { word: "jacqueline", hint: "Bollywood actress of Sri Lankan origin" },
      { word: "taapsee", hint: "Actress known for strong female-led roles" },
      { word: "vidya", hint: "Bollywood actress who starred in Kahaani, Tumhari Sulu" },
      { word: "shraddha", hint: "Actress and singer known for roles in Aashiqui 2, Stree" },
      { word: "nora", hint: "Dancer and actress famous for her item numbers" }
    
    
  ],
  medium: [
      { word: "bachendri", hint: "First Indian woman to climb Mount Everest" },
      { word: "sudha", hint: "First female engineer at TELCO and award-winning author" },
      { word: "anu", hint: "Rocket scientist and Padma Shri awardee" },
      { word: "fathima", hint: "India's first Muslim female pilot" },
      { word: "avani", hint: "First female fighter pilot to fly solo in India" },
      { word: "manju", hint: "Indian javelin thrower and Arjuna award winner" },
      { word: "neerja", hint: "Brave flight attendant who saved lives in a hijack" },
      { word: "puneeta", hint: "Youngest woman officer at Siachen Glacier" },
      { word: "shakuntala", hint: "Mental calculator known as the 'Human Computer'" },
      { word: "karuna", hint: "India's first female judge" },
      { word: "harita", hint: "First Indian woman to fly solo in the Air Force" },
      { word: "tessy", hint: "Project director for Agni missiles, called 'Missile Woman of India'" },
      { word: "valli", hint: "ISRO’s key woman behind Chandrayaan project" },
      { word: "poonam", hint: "First woman to lead an Indian contingent at UN mission" },
      { word: "dhanu", hint: "Martyr who worked in rescue during Kargil war" },
      { word: "maithreyi", hint: "Vedic philosopher and female scholar" },
      { word: "rajni", hint: "First Indian woman to win a medal in Paralympics" },
      { word: "kavita", hint: "International wrestler and MMA fighter" },
      { word: "babita", hint: "Wrestler portrayed in the movie Dangal" },
      { word: "geeta", hint: "First Indian female wrestler to qualify for Olympics" },
      { word: "varsha", hint: "Meteorologist and climate researcher" },
      { word: "moushumi", hint: "Veteran Bengali and Hindi actress" },
      { word: "tejashwini", hint: "Sports shooter and gold medalist" },
      { word: "sita", hint: "Singer and freedom fighter during Independence" },
      { word: "usha", hint: "Classical vocalist of Carnatic music" },
      { word: "meira", hint: "First woman Speaker of Lok Sabha" },
      { word: "malavath", hint: "Young tribal girl to summit Everest at 13" },
      { word: "deepa", hint: "Paralympic athlete and Padma Shri winner" },
      { word: "pratibha", hint: "First woman President of India" },
      { word: "sonal", hint: "Renowned Odissi dancer" }
    
  ],
  hard: [
      { word: "anandibai", hint: "India’s first female physician with Western medical training" },
      { word: "arunima", hint: "First female amputee to scale Mount Everest" },
      { word: "rajkumari", hint: "India’s first female cabinet minister in health" },
      { word: "bhanu", hint: "India’s first female photojournalist" },
      { word: "kamaladevi", hint: "Revived Indian handicrafts and led theater movements" },
      { word: "chandramukhi", hint: "First Indian woman graduate" },
      { word: "hansa", hint: "India’s first woman pilot in the 1930s" },
      { word: "kanaklata", hint: "Teenage freedom fighter shot during Quit India Movement" },
      { word: "padmini", hint: "Legendary Rajput queen known for her sacrifice" },
      { word: "durgabai", hint: "Freedom fighter and founder of Andhra Mahila Sabha" },
      { word: "tarabai", hint: "Queen who led Maratha resistance against Mughals" },
      { word: "lakshmi", hint: "Head of Rani of Jhansi regiment in INA" },
      { word: "begum", hint: "First female ruler of Bhopal" },
      { word: "subhadra", hint: "Poet and freedom fighter known for nationalistic poems" },
      { word: "ammachi", hint: "Spiritual leader known for humanitarian work" },
      { word: "maharani", hint: "Ruler of Travancore, worked for women's rights" },
      { word: "rakhmabai", hint: "One of the first practicing women doctors in India" },
      { word: "aisha", hint: "Educator who worked for women's rights in Kerala" },
      { word: "muthulakshmi", hint: "First woman legislator and social reformer" },
      { word: "gargi", hint: "Ancient Indian philosopher featured in Upanishads" },
      { word: "taramati", hint: "Singer in the court of Golconda kings" },
      { word: "naikidevi", hint: "Queen who led army against Muhammad Ghori" },
      { word: "sister", hint: "Social worker who founded Missionaries of Charity" },
      { word: "mahadevi", hint: "Kannada poet-saint of the 12th century" },
      { word: "savitribai", hint: "India's first woman teacher and feminist icon" },
      { word: "indrani", hint: "India’s first female neurosurgeon" },
      { word: "ilavenil", hint: "Tamil poetess from Sangam age" },
      { word: "panimol", hint: "Medical pioneer and tribal healer in Nagaland" },
      { word: "lalita", hint: "First woman engineer in India" },
      { word: "zohra", hint: "Veteran actress and theater artist" }
    
  ],
  extreme: [
      { word: "rukhmabai", hint: "Pioneer against child marriage and early woman doctor" },
      { word: "sarla", hint: "First Indian woman to fly an aircraft solo in 1936" },
      { word: "urvashi", hint: "India’s first transgender judge" },
      { word: "nandini", hint: "India’s first woman wildlife biologist" },
      { word: "binodini", hint: "First Indian stage actress and writer" },
      { word: "kalpana", hint: "Feminist writer in Bengali literature" },
      { word: "bhanumati", hint: "First female film director in Telugu cinema" },
      { word: "sugandha", hint: "Scientist who developed cancer drugs in India" },
      { word: "mira", hint: "First Indian woman to win an international tennis title" },
      { word: "richa", hint: "Youngest female fighter pilot to complete solo sortie" },
      { word: "jayanti", hint: "First woman from Orissa to climb Everest" },
      { word: "sitalakshmi", hint: "India’s first female pathologist" },
      { word: "rama", hint: "First woman to become President of a political party in India" },
      { word: "bilkis", hint: "Shaheen Bagh protestor known as 'Dadi of Resistance'" },
      { word: "kalavati", hint: "Social worker recognized by President for community service" },
      { word: "vimal", hint: "Pioneer female journalist in early Doordarshan days" },
      { word: "anita", hint: "Paralympic medalist in shot put and discus" },
      { word: "bharti", hint: "Renowned Sanskrit scholar and orator" },
      { word: "karthyayani", hint: "Oldest woman to pass literacy exam in Kerala at 96" },
      { word: "padmavathy", hint: "India’s first female cardiologist" },
      { word: "suman", hint: "Advocate for women's education in rural UP" },
      { word: "shaheen", hint: "Environmental activist from Kashmir" },
      { word: "rosamma", hint: "First female Deputy Speaker of Kerala" },
      { word: "jeevamma", hint: "Social worker honored for rural women development" },
      { word: "dalbir", hint: "Sister of Sarabjit Singh, fought for his justice" },
      { word: "vasundhara", hint: "First female CM of Rajasthan" },
      { word: "margaret", hint: "Freedom fighter and poet from Tamil Nadu" },
      { word: "tara", hint: "Only woman in INA’s Rani Jhansi Brigade to receive military training" },
      { word: "poonam", hint: "Mountaineer and motivational speaker from Himachal" },
      { word: "shanta", hint: "Renowned cancer researcher and doctor" }
    
  ]
  };
  